name: Fly Deploy API
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Set Fly Secrets
        run: |
          cd server
          flyctl secrets set APPOPTIONS__DbConnectionString="${{ secrets.DBCONNECTIONSTRING }}"
          flyctl secrets set APPOPTIONS__JwtSecret="${{ secrets.JWT_SECRET }}"
          flyctl deploy
          fly scale count 1
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_BACKEND }}
