name: Fly Deploy API
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy and Configure Fly #first create toml with "fly app create" after signing in
        run: |
          cd server
          # Set scale to 1 before deployment to ensure we never exceed 1 machine
          flyctl scale count 1
          # Set secrets
          flyctl secrets set \
            APPOPTIONS__DbConnectionString="${{ secrets.DBCONNECTIONSTRING }}" \
            APPOPTIONS__JwtSecret="${{ secrets.JWT_SECRET }}"
          # Deploy
          flyctl deploy --ha=false
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_BACKEND }} #fly tokens create deploy