name: Fly Deploy API
on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: cd server && flyctl deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          APPOPTIONS__DbConnectionString: ${{secrets.DBCONNECTIONSTRING}}
          APPOPTIONS__JwtSecret: ${{secrets.JWT_SECRET}}
