name: .NET Tests

on:
  workflow_dispatch:
  push:

jobs:
  local_development:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9'
      - uses: docker/setup-buildx-action@v3
      - run: cd template_onion_with_mqtt/server/Startup.Tests && dotnet test
        timeout-minutes: 10
        env:
          APPOPTIONS__DbConnectionString: ${{secrets.DBCONNECTIONSTRING}}
          APPOPTIONS__JwtSecret: ${{secrets.JWT_SECRET}}
