name: .NET Tests

on:
  workflow_dispatch:

jobs:
  dotnet-tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9'
      - uses: docker/setup-buildx-action@v3
      - run: cd server/tests && dotnet test
        timeout-minutes: 10
        env:
          APPOPTIONS__JwtSecret: ${{secrets.JWT_SECRET}}
          APPOPTIONS__RunsOn: "GitHub"
